# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8551bca22eb76eff5db3eb4f6019e6e27bb2d942eaab3646591dbfa6f43e8a5a7fd55c86d5a65d8098318b5de9b3e24fc848e425e6c2ecadb3e50c607c185f49

test:
  secret_key_base: f89dd4eafc33720f1355686c9593b8890c2b63585c6db193c6445f6d8976b8079ab8cbfeb3d883ca12415be80fe9fe651616463356f3b0d9e0d11d9e03387aea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
